# Generated by Django 3.2.7 on 2021-12-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200, unique=True)),
                ('Eventname', models.CharField(max_length=200)),
                ('Esize', models.IntegerField()),
                ('Evenue', models.CharField(max_length=200)),
                ('Rooms', models.IntegerField()),
                ('Foodfacility', models.BooleanField(default=False)),
                ('Wifi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=100)),
                ('contactNumber', models.IntegerField(unique=True)),
                ('relation', models.CharField(max_length=200)),
                ('Organiser_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventfacility')),
            ],
        ),
    ]
