# Generated by Django 3.2.7 on 2021-12-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFacility1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200, unique=True)),
                ('Eventname', models.CharField(max_length=200)),
                ('Esize', models.IntegerField()),
                ('Evenue', models.CharField(max_length=200)),
                ('Rooms', models.IntegerField()),
                ('Foodfacility', models.BooleanField(default=False)),
                ('Wifi', models.BooleanField(default=False)),
                ('status', models.BooleanField(choices=[('Publish', 'Publish'), ('Not Publish', 'Not Publish')], default='Not Publish')),
            ],
        ),
    ]
