# Generated by Django 3.2.7 on 2021-12-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventfacility1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventFacility1',
        ),
    ]
