# Generated by Django 3.2.7 on 2021-12-31 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_delete_eventfacility1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishEvent',
            fields=[
                ('eventfacility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.eventfacility')),
            ],
            bases=('event.eventfacility',),
        ),
        migrations.AddField(
            model_name='eventfacility',
            name='Publish',
            field=models.BooleanField(default=False),
        ),
    ]
