# Generated by Django 3.2.7 on 2021-12-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_eventfacility_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfacility',
            name='Publish',
            field=models.BooleanField(default=False),
        ),
    ]
